import descEscooters from './description'
import reviewsEscooters from './reviews'
import specEscooters from './specs'
import img from './img'

const eScooters = [
	{
		id: 'es_01',
		scu: 'RE9001',
		link: 'razor_e90_black-label',
		category: 'eScooter',
		type: 'Электросамокат',
		manufacturer: 'Razor',
		model: 'Black Label E90',
		img: [
			img.blackLabelE90.blackLabelE90_01,
			img.blackLabelE90.blackLabelE90_02,
			img.blackLabelE90.blackLabelE90_03,
			img.blackLabelE90.blackLabelE90_04,
			img.blackLabelE90.blackLabelE90_05
		],
		ePower: true,
		colors: ['green', 'pink'],
		price: '23 990 р.',
		discountPrice: '15 990 р.',
		rating: 4.3,
		labels: [],
		inStock: true,
		warranty: '6 месяцев',
		desc: descEscooters.blackLabelE90.desc,
		reviews: reviewsEscooters.blackLabelE90.reviews,
		spec: specEscooters.blackLabelE90,
		// buyTogether: []
	},
	{
		id: 'es_02',
		scu: 'RE10002',
		link: 'razor_e100_black-label',
		category: 'eScooter',
		type: 'Электросамокат',
		manufacturer: 'Razor',
		model: 'Black Label E100',
		img: [
			img.blackLabelE100.blackLabelE100_01,
			img.blackLabelE100.blackLabelE100_02,
			img.blackLabelE100.blackLabelE100_03,
			img.blackLabelE100.blackLabelE100_04,
			img.blackLabelE100.blackLabelE100_05
		],
		ePower: true,
		colors: ['red', 'purple', 'blue'],
		price: '25 990 р.',
		discountPrice: '17 790 р.',
		rating: 4.8,
		labels: ['новинка'],
		inStock: true,
		warranty: '6 месяцев',
		desc: descEscooters.blackLabelE100.desc,
		reviews: reviewsEscooters.blackLabelE100.reviews,
		spec: specEscooters.blackLabelE100,
		// buyTogether: []
	},
	{
		id: 'es_03',
		scu: 'RC2503',
		link: 'razor_c25',
		category: 'eScooter',
		type: 'Электросамокат',
		manufacturer: 'Razor',
		model: 'C25',
		img: [img.c25.c25_01, img.c25.c25_02, img.c25.c25_03, img.c25.c25_04, img.c25.c25_05],
		ePower: true,
		colors: 'grey',
		price: '59 990 р.',
		discountPrice: '48 990 р.',
		rating: 4,
		labels: ['новинка'],
		inStock: true,
		warranty: '6 месяцев',
		desc: descEscooters.c25.desc,
		reviews: reviewsEscooters.c25.reviews,
		spec: specEscooters.c25,
		// buyTogether: []
	},
	{
		id: 'es_04',
		scu: 'RC35SLA04',
		link: 'razor_c35_sla',
		category: 'eScooter',
		type: 'Электросамокат',
		manufacturer: 'Razor',
		model: 'C35 SLA',
		img: [img.c35SLA.c35SLA_01, img.c35SLA.c35SLA_02, img.c35SLA.c35SLA_03, img.c35SLA.c35SLA_04, img.c35SLA.c35SLA_05],
		ePower: true,
		colors: 'beige',
		price: '54 990 р.',
		discountPrice: '46 990 р.',
		rating: 3.8,
		labels: ['новинка'],
		inStock: true,
		warranty: '6 месяцев',
		desc: descEscooters.c35sla.desc,
		reviews: reviewsEscooters.c35sla.reviews,
		spec: specEscooters.c35sla,
		// buyTogether: []
	},
	{
		id: 'es_05',
		scu: 'RC4505',
		link: 'razor_c45',
		category: 'eScooter',
		type: 'Электросамокат',
		manufacturer: 'Razor',
		model: 'C45',
		img: [img.c45.c45_01, img.c45.c45_02, img.c45.c45_03, img.c45.c45_04, img.c45.c45_05],
		ePower: true,
		colors: 'black',
		price: '72 990 р.',
		discountPrice: '60 990 р.',
		rating: 5,
		labels: ['хит продаж'],
		inStock: true,
		warranty: '6 месяцев',
		desc: descEscooters.c45.desc,
		reviews: reviewsEscooters.c45.reviews,
		spec: specEscooters.c45,
		// buyTogether: []
	}
]

export default eScooters
